export const TEXTS = {
  fa: {
    title: 'ذهن‌خوان',
    subtitle: 'به یک عدد فکر کن… ما آن را پیدا می‌کنیم',
    guide: 'نیازی به گفتن یا نوشتن عدد نیست. فقط صادقانه پاسخ بده',
    selectANumber: 'یک عدد از 1 تا 100 انتخاب کن',
    hint: 'آیا عددی که در ذهن داری، در این کارت وجود دارد؟',
    yes: 'بله',
    no: 'خیر',
    reveal: 'آشکارسازی حقیقت',
    resultTitle: 'عدد تو این است',
    resultSubtitle: 'همان عددی که از ابتدا در ذهنت بود',
    restart: 'شروع دوباره',
    footer: 'طراحی و پیاده‌سازی: علی احمدی‌نسب',
  },
  en: {
    title: 'Astral Cipher',
    subtitle: 'Think of a number… We will reveal it.',
    guide: 'You don’t need to type or say your number. Just answer honestly.',
    selectANumber: 'Select A Number between 1 & 100',
    hint: 'Does your number appear on this card?',
    yes: 'YES',
    no: 'NO',
    reveal: 'Bind the Truth',
    resultTitle: 'Your Number Is',
    resultSubtitle: 'The number you had in mind all along.',
    restart: 'Restart',
    footer: 'Designed & Developed by Ali Ahmadi Nasab',
  },
};
