export const TEXTS = {
  fa: {
    title: 'اوراکل سن',
    subtitle: 'به عددی فکر کن؛ پاسخ از پیش روشن است',
    guide: 'عدد را در ذهن نگه دار و تنها با آری یا نه پاسخ بده',
    selectANumber: 'شروع بازی',
    cardNumber: 'کارت',
    yes: 'بله',
    no: 'خیر',
    reveal: 'نمایش نتیجه',
    resultTitle: 'عدد نهایی',
    resultSubtitle: 'همان عددی که از ابتدا در ذهن داشتی',
    restart: 'شروع دوباره',
    footer: 'طراحی و پیاده‌سازی: علی احمدی‌نسب',
  },

  en: {
    title: 'Age Oracle',
    subtitle: 'Think of a number. The answer is already known.',
    guide: 'Keep the number in mind and answer only yes or no',
    selectANumber: 'Start',
    cardNumber: 'Card',
    yes: 'Yes',
    no: 'No',
    reveal: 'Reveal Result',
    resultTitle: 'Final Number',
    resultSubtitle: 'The number you had in mind from the beginning',
    restart: 'Restart',
    footer: 'Designed & Developed by Ali Ahmadi Nasab',
  },
};
